//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.NET.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finances.NET.Resources.Language.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto raderat..
        /// </summary>
        internal static string ACCOUNT_DELETED {
            get {
                return ResourceManager.GetString("ACCOUNT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoinformation laddad..
        /// </summary>
        internal static string ACCOUNTS_DATA_LOAD_FINISHED {
            get {
                return ResourceManager.GetString("ACCOUNTS_DATA_LOAD_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto fil. (*.cna)|*.cna.
        /// </summary>
        internal static string ACCOUNTS_FILE {
            get {
                return ResourceManager.GetString("ACCOUNTS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoinformation sparad..
        /// </summary>
        internal static string ACCOUNTS_SAVED {
            get {
                return ResourceManager.GetString("ACCOUNTS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo :.
        /// </summary>
        internal static string BALANCE {
            get {
                return ResourceManager.GetString("BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo datum: .
        /// </summary>
        internal static string BALANCE_AT {
            get {
                return ResourceManager.GetString("BALANCE_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramtillägg.
        /// </summary>
        internal static string CHARTS_PLUGINS {
            get {
                return ResourceManager.GetString("CHARTS_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekrypterar kontoinformation från fil: .
        /// </summary>
        internal static string DECRYPTING_ACCOUNTS_FILE {
            get {
                return ResourceManager.GetString("DECRYPTING_ACCOUNTS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radera.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera transaktion.
        /// </summary>
        internal static string EDIT_TRANSACTION {
            get {
                return ResourceManager.GetString("EDIT_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krypterad fil. (*.cne)|*.cne.
        /// </summary>
        internal static string ENCRYPTED_ACCOUNTS_FILE {
            get {
                return ResourceManager.GetString("ENCRYPTED_ACCOUNTS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krypterad kontoinformation sparad..
        /// </summary>
        internal static string ENCRYPTED_ACCOUNTS_SAVED {
            get {
                return ResourceManager.GetString("ENCRYPTED_ACCOUNTS_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krypterar data och sparar till vald fil: .
        /// </summary>
        internal static string ENCRYPTING_DATA_XML_FILE {
            get {
                return ResourceManager.GetString("ENCRYPTING_DATA_XML_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var god skriv in krypteringlösenordet nedan..
        /// </summary>
        internal static string ENTER_ACCOUNT_PASSWORD {
            get {
                return ResourceManager.GetString("ENTER_ACCOUNT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel upstod vid laddning av filen..
        /// </summary>
        internal static string FILE_LOAD_ERROR {
            get {
                return ResourceManager.GetString("FILE_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avslutar konto initialisering..
        /// </summary>
        internal static string FINALIZING_ACCOUNT_SETUP {
            get {
                return ResourceManager.GetString("FINALIZING_ACCOUNT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programtillägg.
        /// </summary>
        internal static string FUNCTIONS_PLUGINS {
            get {
                return ResourceManager.GetString("FUNCTIONS_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialiserar konton..
        /// </summary>
        internal static string INITIALIZING_ACCOUNTS {
            get {
                return ResourceManager.GetString("INITIALIZING_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laddar kontoinformation från fil: .
        /// </summary>
        internal static string LOADING_ACCOUNTS_FILE {
            get {
                return ResourceManager.GetString("LOADING_ACCOUNTS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Inget konto laddat&gt;.
        /// </summary>
        internal static string NO_ACCOUNT_LOADED {
            get {
                return ResourceManager.GetString("NO_ACCOUNT_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Övriga tillägg.
        /// </summary>
        internal static string OTHER_PLUGINS {
            get {
                return ResourceManager.GetString("OTHER_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapporttillägg.
        /// </summary>
        internal static string REPORTS_PLUGINS {
            get {
                return ResourceManager.GetString("REPORTS_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparar data till vald fil: .
        /// </summary>
        internal static string SAVING_DATA_XML_FILE {
            get {
                return ResourceManager.GetString("SAVING_DATA_XML_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemalagd transaktion raderad..
        /// </summary>
        internal static string SCHEDULED_OPERATION_REMOVED {
            get {
                return ResourceManager.GetString("SCHEDULED_OPERATION_REMOVED", resourceCulture);
            }
        }
    }
}
